export const dom = {
  startAfter: document.getElementById("startAfter"),
  endBefore: document.getElementById("endBefore"),
  sportFilterChips: document.getElementById("sportFilterChips"),
  statusFilterChips: document.getElementById("statusFilterChips"),
  teamFilterList: document.getElementById("teamFilterList"),
  loadEventsBtn: document.getElementById("loadEventsBtn"),
  clearFiltersBtn: document.getElementById("clearFiltersBtn"),
  eventsList: document.getElementById("eventsList"),
  eventsCount: document.getElementById("eventsCount"),
  openCreateModalBtn: document.getElementById("openCreateModalBtn"),
  createModal: document.getElementById("createModal"),
  createModalBackdrop: document.getElementById("createModalBackdrop"),
  closeCreateModalBtn: document.getElementById("closeCreateModalBtn"),
  cancelCreateBtn: document.getElementById("cancelCreateBtn"),
  sportCreate: document.getElementById("sportCreate"),
  competitionCreate: document.getElementById("competitionCreate"),
  venueCreate: document.getElementById("venueCreate"),
  teamOne: document.getElementById("teamOne"),
  teamTwo: document.getElementById("teamTwo"),
  startTimeCreate: document.getElementById("startTimeCreate"),
  createEventBtn: document.getElementById("createEventBtn"),
  createMsg: document.getElementById("createMsg")
}
