server {
    listen 5050;
    server_name _;

    location /files/ {
        proxy_pass http://fileserver:80/;
    }
    
    location /api/ {
        proxy_pass http://server:8080/api/;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri /index.html = 404;
    }
}
