// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompetitionType string

const (
	CompetitionTypeTournament CompetitionType = "tournament"
	CompetitionTypeLeague     CompetitionType = "league"
	CompetitionTypeFriendly   CompetitionType = "friendly"
	CompetitionTypeOther      CompetitionType = "other"
)

func (e *CompetitionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompetitionType(s)
	case string:
		*e = CompetitionType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompetitionType: %T", src)
	}
	return nil
}

type NullCompetitionType struct {
	CompetitionType CompetitionType
	Valid           bool // Valid is true if CompetitionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompetitionType) Scan(value interface{}) error {
	if value == nil {
		ns.CompetitionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompetitionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompetitionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompetitionType), nil
}

type StageName string

const (
	StageNameGroupstage StageName = "group stage"
	StageName164        StageName = "1/64"
	StageName132        StageName = "1/32"
	StageName116        StageName = "1/16"
	StageName18         StageName = "1/8"
	StageName14         StageName = "1/4"
	StageName12         StageName = "1/2"
	StageNameFinal      StageName = "final"
)

func (e *StageName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StageName(s)
	case string:
		*e = StageName(s)
	default:
		return fmt.Errorf("unsupported scan type for StageName: %T", src)
	}
	return nil
}

type NullStageName struct {
	StageName StageName
	Valid     bool // Valid is true if StageName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStageName) Scan(value interface{}) error {
	if value == nil {
		ns.StageName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StageName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStageName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StageName), nil
}

type Status string

const (
	StatusScheduled  Status = "scheduled"
	StatusInprogress Status = "in progress"
	StatusFinished   Status = "finished"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status
	Valid  bool // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type City struct {
	CityID    int32
	CountryID *int32
	Name      string
}

type Competition struct {
	CompetitionID int32
	SportID       int32
	Type          CompetitionType
	Name          string
	LogoPath      *string
}

type CompetitionTeam struct {
	CompetitionTeamID int32
	CompetitionID     int32
	TeamID            int32
}

type Country struct {
	CountryID int32
	Name      string
	Code      string
}

type Event struct {
	EventID       int32
	CompetitionID int32
	VenueID       int32
	StageID       int32
	Status        Status
	StartTime     time.Time
	EndTime       pgtype.Timestamptz
}

type Participant struct {
	ParticipantID int32
	EventID       int32
	TeamID        int32
}

type Player struct {
	PlayerID    int32
	TeamID      int32
	CountryID   *int32
	FirstName   string
	LastName    string
	ShirtNumber int32
	BirthDate   pgtype.Date
	Height      int32
}

type Playground struct {
	PlaygroundID int32
	SportID      int32
	VenueID      int32
}

type Score struct {
	ScoreID       int32
	ParticipantID int32
	Segment       int16
	Score         int32
}

type Sport struct {
	SportID int32
	Name    string
}

type Stage struct {
	StageID    int32
	Name       StageName
	RoundOrder int32
}

type Team struct {
	TeamID       int32
	SportID      int32
	CityID       *int32
	Name         string
	Abbreviation string
	LogoPath     *string
}

type Venue struct {
	VenueID  int32
	CityID   int32
	Name     string
	Capacity int16
}
