// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CountValidTeamsForCompetition(ctx context.Context, arg CountValidTeamsForCompetitionParams) (int64, error)
	GetDetailedEventByID(ctx context.Context, eventID int32) (GetDetailedEventByIDRow, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (int32, error)
	InsertParticipants(ctx context.Context, arg InsertParticipantsParams) error
	IsVenueValidForCompetition(ctx context.Context, arg IsVenueValidForCompetitionParams) (bool, error)
	ListCompetitionsBySportID(ctx context.Context, sportID int32) ([]ListCompetitionsBySportIDRow, error)
	ListDetailedTeamsByEventID(ctx context.Context, eventID int32) ([]ListDetailedTeamsByEventIDRow, error)
	ListEventsByFilter(ctx context.Context, arg ListEventsByFilterParams) ([]ListEventsByFilterRow, error)
	ListFinalScoresByEventsIDs(ctx context.Context, eventIds []int32) ([]ListFinalScoresByEventsIDsRow, error)
	ListPlayersByTeamIDs(ctx context.Context, teamIds []int32) ([]ListPlayersByTeamIDsRow, error)
	ListScoresByEventID(ctx context.Context, eventID int32) ([]ListScoresByEventIDRow, error)
	ListSports(ctx context.Context) ([]Sport, error)
	ListTeamsByCompetitionID(ctx context.Context, competitionID int32) ([]ListTeamsByCompetitionIDRow, error)
	ListTeamsByEventsIDs(ctx context.Context, eventIds []int32) ([]ListTeamsByEventsIDsRow, error)
	ListTeamsBySportID(ctx context.Context, sportID int32) ([]ListTeamsBySportIDRow, error)
	ListVenuesBySportID(ctx context.Context, sportID int32) ([]ListVenuesBySportIDRow, error)
}

var _ Querier = (*Queries)(nil)
