// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countValidTeamsForCompetition = `-- name: CountValidTeamsForCompetition :one
SELECT COUNT(DISTINCT ct._team_id)
FROM competition_teams ct
WHERE 
    ct._competition_id = $1
    AND ct._team_id = ANY($2::int[])
`

type CountValidTeamsForCompetitionParams struct {
	CompetitionID int32
	TeamIds       []int32
}

func (q *Queries) CountValidTeamsForCompetition(ctx context.Context, arg CountValidTeamsForCompetitionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countValidTeamsForCompetition, arg.CompetitionID, arg.TeamIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDetailedEventByID = `-- name: GetDetailedEventByID :one
SELECT 
    e.event_id, 
    e.start_time,
    e.end_time,
    e.status,
    s.name AS sport_name,
    c.name AS competition_name,
    v.name AS venue_name
FROM events e
JOIN venues v ON v.venue_id = e._venue_id 
JOIN competitions c ON c.competition_id = e._competition_id
JOIN sports s ON s.sport_id = c._sport_id 
WHERE e.event_id = $1
`

type GetDetailedEventByIDRow struct {
	EventID         int32
	StartTime       time.Time
	EndTime         pgtype.Timestamptz
	Status          Status
	SportName       string
	CompetitionName string
	VenueName       string
}

func (q *Queries) GetDetailedEventByID(ctx context.Context, eventID int32) (GetDetailedEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getDetailedEventByID, eventID)
	var i GetDetailedEventByIDRow
	err := row.Scan(
		&i.EventID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.SportName,
		&i.CompetitionName,
		&i.VenueName,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (_competition_id, _venue_id, _stage_id, status, start_time) 
VALUES ($1, $2, $3, $4, $5)
RETURNING event_id
`

type InsertEventParams struct {
	CompetitionID int32
	VenueID       int32
	StageID       int32
	Status        Status
	StartTime     time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.CompetitionID,
		arg.VenueID,
		arg.StageID,
		arg.Status,
		arg.StartTime,
	)
	var event_id int32
	err := row.Scan(&event_id)
	return event_id, err
}

const insertParticipants = `-- name: InsertParticipants :exec
INSERT INTO participants (_event_id, _team_id) 
SELECT 
    $1,
    unnest($2::int[])
`

type InsertParticipantsParams struct {
	EventID  int32
	TeamsIds []int32
}

func (q *Queries) InsertParticipants(ctx context.Context, arg InsertParticipantsParams) error {
	_, err := q.db.Exec(ctx, insertParticipants, arg.EventID, arg.TeamsIds)
	return err
}

const isVenueValidForCompetition = `-- name: IsVenueValidForCompetition :one
SELECT EXISTS (
    SELECT 1
    FROM competitions c
    JOIN playgrounds p on p._sport_id = c._sport_id
    WHERE 
        c.competition_id = $1
        AND p._venue_id = $2
)
`

type IsVenueValidForCompetitionParams struct {
	CompetitionID int32
	VenueID       int32
}

func (q *Queries) IsVenueValidForCompetition(ctx context.Context, arg IsVenueValidForCompetitionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isVenueValidForCompetition, arg.CompetitionID, arg.VenueID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCompetitionsBySportID = `-- name: ListCompetitionsBySportID :many
SELECT 
    c.competition_id,
    c.name
FROM competitions c
WHERE c._sport_id = $1
`

type ListCompetitionsBySportIDRow struct {
	CompetitionID int32
	Name          string
}

func (q *Queries) ListCompetitionsBySportID(ctx context.Context, sportID int32) ([]ListCompetitionsBySportIDRow, error) {
	rows, err := q.db.Query(ctx, listCompetitionsBySportID, sportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompetitionsBySportIDRow
	for rows.Next() {
		var i ListCompetitionsBySportIDRow
		if err := rows.Scan(&i.CompetitionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetailedTeamsByEventID = `-- name: ListDetailedTeamsByEventID :many
SELECT 
    p._event_id,
    t.team_id,
    t.name,
    t.abbreviation,
    t.logo_path,
    ci.name AS city_name,
    co.name AS country_name,
    co.code AS country_code
FROM participants p
JOIN teams t ON t.team_id = p._team_id
JOIN cities ci ON ci.city_id = t._city_id
JOIN countries co ON co.country_id = ci._country_id
WHERE p._event_id = $1
`

type ListDetailedTeamsByEventIDRow struct {
	EventID      int32
	TeamID       int32
	Name         string
	Abbreviation string
	LogoPath     *string
	CityName     string
	CountryName  string
	CountryCode  string
}

func (q *Queries) ListDetailedTeamsByEventID(ctx context.Context, eventID int32) ([]ListDetailedTeamsByEventIDRow, error) {
	rows, err := q.db.Query(ctx, listDetailedTeamsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDetailedTeamsByEventIDRow
	for rows.Next() {
		var i ListDetailedTeamsByEventIDRow
		if err := rows.Scan(
			&i.EventID,
			&i.TeamID,
			&i.Name,
			&i.Abbreviation,
			&i.LogoPath,
			&i.CityName,
			&i.CountryName,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByFilter = `-- name: ListEventsByFilter :many
SELECT 
    e.event_id, 
    e.start_time,
    e.status,
    s.name AS sport_name,
    c.name AS competition_name 
FROM events e 
JOIN competitions c ON c.competition_id = e._competition_id
JOIN sports s ON s.sport_id = c._sport_id 
WHERE 
    e.start_time >= $1
    AND e.start_time <= $2
    AND c._sport_id = COALESCE($3, c._sport_id) 
    AND e._competition_id = COALESCE($4, e._competition_id) 
    AND $5::int[] IS NULL OR EXISTS 
      (SELECT 1 FROM participants p
      WHERE p._event_id = e.event_id
        AND p._team_id = ANY($5::int[]))
`

type ListEventsByFilterParams struct {
	StartAfter    time.Time
	EndBefore     time.Time
	SportID       *int32
	CompetitionID *int32
	TeamIds       []int32
}

type ListEventsByFilterRow struct {
	EventID         int32
	StartTime       time.Time
	Status          Status
	SportName       string
	CompetitionName string
}

func (q *Queries) ListEventsByFilter(ctx context.Context, arg ListEventsByFilterParams) ([]ListEventsByFilterRow, error) {
	rows, err := q.db.Query(ctx, listEventsByFilter,
		arg.StartAfter,
		arg.EndBefore,
		arg.SportID,
		arg.CompetitionID,
		arg.TeamIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsByFilterRow
	for rows.Next() {
		var i ListEventsByFilterRow
		if err := rows.Scan(
			&i.EventID,
			&i.StartTime,
			&i.Status,
			&i.SportName,
			&i.CompetitionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayersByTeamIDs = `-- name: ListPlayersByTeamIDs :many
SELECT
    p.player_id,
    p._team_id,
    p.first_name,
    p.last_name,
    co.name AS country_name,
    co.code AS country_code
FROM players p
JOIN countries co ON co.country_id = p._country_id
WHERE p._team_id = ANY($1::int[])
`

type ListPlayersByTeamIDsRow struct {
	PlayerID    int32
	TeamID      int32
	FirstName   string
	LastName    string
	CountryName string
	CountryCode string
}

func (q *Queries) ListPlayersByTeamIDs(ctx context.Context, teamIds []int32) ([]ListPlayersByTeamIDsRow, error) {
	rows, err := q.db.Query(ctx, listPlayersByTeamIDs, teamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersByTeamIDsRow
	for rows.Next() {
		var i ListPlayersByTeamIDsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.TeamID,
			&i.FirstName,
			&i.LastName,
			&i.CountryName,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoresByEventID = `-- name: ListScoresByEventID :many
SELECT
    p._team_id,
    s.segment,
    s.score
FROM participants p
JOIN scores s ON s._participant_id = p.participant_id
WHERE p._event_id = $1
`

type ListScoresByEventIDRow struct {
	TeamID  int32
	Segment int16
	Score   int32
}

func (q *Queries) ListScoresByEventID(ctx context.Context, eventID int32) ([]ListScoresByEventIDRow, error) {
	rows, err := q.db.Query(ctx, listScoresByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScoresByEventIDRow
	for rows.Next() {
		var i ListScoresByEventIDRow
		if err := rows.Scan(&i.TeamID, &i.Segment, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSports = `-- name: ListSports :many
SELECT sport_id, name FROM sports
`

func (q *Queries) ListSports(ctx context.Context) ([]Sport, error) {
	rows, err := q.db.Query(ctx, listSports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sport
	for rows.Next() {
		var i Sport
		if err := rows.Scan(&i.SportID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByCompetitionID = `-- name: ListTeamsByCompetitionID :many
SELECT 
    t.team_id,
    t.name,
    t.abbreviation,
    t.logo_path
FROM teams t
JOIN competition_teams ct ON t.team_id = ct._team_id
WHERE ct._competition_id = $1
`

type ListTeamsByCompetitionIDRow struct {
	TeamID       int32
	Name         string
	Abbreviation string
	LogoPath     *string
}

func (q *Queries) ListTeamsByCompetitionID(ctx context.Context, competitionID int32) ([]ListTeamsByCompetitionIDRow, error) {
	rows, err := q.db.Query(ctx, listTeamsByCompetitionID, competitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsByCompetitionIDRow
	for rows.Next() {
		var i ListTeamsByCompetitionIDRow
		if err := rows.Scan(
			&i.TeamID,
			&i.Name,
			&i.Abbreviation,
			&i.LogoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByEventsIDs = `-- name: ListTeamsByEventsIDs :many
SELECT 
    p._event_id,
    t.team_id,
    t.name,
    t.abbreviation,
    t.logo_path
FROM participants p
JOIN teams t ON t.team_id = p._team_id
WHERE p._event_id = ANY($1::int[])
`

type ListTeamsByEventsIDsRow struct {
	EventID      int32
	TeamID       int32
	Name         string
	Abbreviation string
	LogoPath     *string
}

func (q *Queries) ListTeamsByEventsIDs(ctx context.Context, eventIds []int32) ([]ListTeamsByEventsIDsRow, error) {
	rows, err := q.db.Query(ctx, listTeamsByEventsIDs, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsByEventsIDsRow
	for rows.Next() {
		var i ListTeamsByEventsIDsRow
		if err := rows.Scan(
			&i.EventID,
			&i.TeamID,
			&i.Name,
			&i.Abbreviation,
			&i.LogoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuesBySportID = `-- name: ListVenuesBySportID :many
SELECT 
    v.venue_id,
    v.name,
    v.capacity,
    ci.name AS city_name,
    co.name AS country_name,
    co.code AS country_code
FROM venues v
JOIN playgrounds p ON p._venue_id = v.venue_id
JOIN cities ci ON ci.city_id = v._city_id
JOIN countries co ON co.country_id = ci._country_id
WHERE p._sport_id = $1
`

type ListVenuesBySportIDRow struct {
	VenueID     int32
	Name        string
	Capacity    int16
	CityName    string
	CountryName string
	CountryCode string
}

func (q *Queries) ListVenuesBySportID(ctx context.Context, sportID int32) ([]ListVenuesBySportIDRow, error) {
	rows, err := q.db.Query(ctx, listVenuesBySportID, sportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVenuesBySportIDRow
	for rows.Next() {
		var i ListVenuesBySportIDRow
		if err := rows.Scan(
			&i.VenueID,
			&i.Name,
			&i.Capacity,
			&i.CityName,
			&i.CountryName,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
