// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
	"time"
)

const listEventTeams = `-- name: ListEventTeams :many
SELECT 
    p._event_id,
    t.team_id,
    t.name,
    t.abbreviation,
    t.logo_path
FROM participants p
JOIN teams t ON t.team_id =  p._team_id
WHERE p._event_id = ANY($1::int[])
`

type ListEventTeamsRow struct {
	EventID      int32
	TeamID       int32
	Name         string
	Abbreviation string
	LogoPath     *string
}

func (q *Queries) ListEventTeams(ctx context.Context, eventIds []int32) ([]ListEventTeamsRow, error) {
	rows, err := q.db.Query(ctx, listEventTeams, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventTeamsRow
	for rows.Next() {
		var i ListEventTeamsRow
		if err := rows.Scan(
			&i.EventID,
			&i.TeamID,
			&i.Name,
			&i.Abbreviation,
			&i.LogoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilteredEvents = `-- name: ListFilteredEvents :many
SELECT 
    e.event_id, 
    e.start_time,
    e.end_time,
    e.status,
    s.name AS sport_name,
    c.name AS competition_name 
FROM events e 
JOIN competitions c ON c.competition_id = e._competition_id
JOIN sports s ON s.sport_id = c._sport_id 
WHERE 
    e.start_time >= $1
    AND e.end_time <= $2
    AND c._sport_id = COALESCE($3, c._sport_id) 
    AND e._competition_id = COALESCE($4, e._competition_id) 
    AND $5::int[] IS NULL OR EXISTS 
      (SELECT 1
      FROM participants p
      WHERE p._event_id = e.event_id
        AND p._team_id = ANY($5::int[]))
`

type ListFilteredEventsParams struct {
	StartAfter    time.Time
	EndBefore     time.Time
	SportID       *int32
	CompetitionID *int32
	TeamIds       []int32
}

type ListFilteredEventsRow struct {
	EventID         int32
	StartTime       time.Time
	EndTime         time.Time
	Status          Status
	SportName       string
	CompetitionName string
}

func (q *Queries) ListFilteredEvents(ctx context.Context, arg ListFilteredEventsParams) ([]ListFilteredEventsRow, error) {
	rows, err := q.db.Query(ctx, listFilteredEvents,
		arg.StartAfter,
		arg.EndBefore,
		arg.SportID,
		arg.CompetitionID,
		arg.TeamIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilteredEventsRow
	for rows.Next() {
		var i ListFilteredEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.SportName,
			&i.CompetitionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
